
package upeu.edu.pe.casos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sueldoDao", targetNamespace = "http://casos.pe.edu.upeu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SueldoDao {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sueldo", targetNamespace = "http://casos.pe.edu.upeu/", className = "upeu.edu.pe.casos.Sueldo")
    @ResponseWrapper(localName = "sueldoResponse", targetNamespace = "http://casos.pe.edu.upeu/", className = "upeu.edu.pe.casos.SueldoResponse")
    @Action(input = "http://casos.pe.edu.upeu/sueldosDao/sueldoRequest", output = "http://casos.pe.edu.upeu/sueldosDao/sueldoResponse")
    public double sueldo(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
